# Generated by Django 4.1.7 on 2023-02-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(db_column='run')),
                ('PDU', models.IntegerField(db_column='PDU')),
                ('CET', models.IntegerField(db_column='CET')),
                ('STU', models.IntegerField(db_column='STU')),
                ('start_date', models.DateField(db_column='start_date')),
                ('time', models.CharField(db_column='time', max_length=20)),
                ('day_period', models.CharField(db_column='day_period', max_length=20)),
                ('end_date', models.DateField(db_column='end_date')),
                ('max_seats', models.IntegerField(db_column='max_seat')),
                ('fee', models.IntegerField(db_column='fee')),
                ('confirmation_email', models.CharField(choices=[('1 day Before', '1 day Before'), ('2 day Before', '2 day Before'), ('3 day Before', '3 day Before')], db_column='confirmation_email', max_length=20)),
                ('certificate_email', models.CharField(choices=[('1 day After', '1 day After'), ('2 day After', '2 day After'), ('3 day After', '3 day After'), ('Immediate After Attendance', 'Immediate After Attendance')], db_column='certificate_email', max_length=30)),
                ('visibility', models.CharField(db_column='visibility', default='UnHide', max_length=10)),
                ('select_course', models.ForeignKey(db_column='select_course', on_delete=django.db.models.deletion.PROTECT, to='courses_be.course')),
            ],
            options={
                'db_table': 'schedule_course',
            },
        ),
    ]
